import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@ntla9aw/trpc-client/src/Provider";
import { SessionProvider } from "@ntla9aw/ui/src/components/molecules/SessionProvider";
import CustomLayout from "@ntla9aw/ui/src/components/molecules/CustomLayout";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Provider>
            <CustomLayout>{children}</CustomLayout>
          </Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
